// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApNaYWF38uUIB8BCH2DDBowN5fNU5SMck',
    appId: '1:404364776018:web:55d1b273a13b917cd1058b',
    messagingSenderId: '404364776018',
    projectId: 'teddysitdb',
    authDomain: 'teddysitdb.firebaseapp.com',
    storageBucket: 'teddysitdb.firebasestorage.app',
    measurementId: 'G-23MJ9KGKYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxfny9fX9owAf48AU5brHcMXD978Idq60',
    appId: '1:404364776018:android:5033dada3a703dfbd1058b',
    messagingSenderId: '404364776018',
    projectId: 'teddysitdb',
    storageBucket: 'teddysitdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCric7NZmi2fSDpa46ZvgZiyZdNXmvge_g',
    appId: '1:404364776018:ios:b104032602e138eed1058b',
    messagingSenderId: '404364776018',
    projectId: 'teddysitdb',
    storageBucket: 'teddysitdb.firebasestorage.app',
    iosBundleId: 'com.example.teddySit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCric7NZmi2fSDpa46ZvgZiyZdNXmvge_g',
    appId: '1:404364776018:ios:b104032602e138eed1058b',
    messagingSenderId: '404364776018',
    projectId: 'teddysitdb',
    storageBucket: 'teddysitdb.firebasestorage.app',
    iosBundleId: 'com.example.teddySit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApNaYWF38uUIB8BCH2DDBowN5fNU5SMck',
    appId: '1:404364776018:web:a1129b4528793eecd1058b',
    messagingSenderId: '404364776018',
    projectId: 'teddysitdb',
    authDomain: 'teddysitdb.firebaseapp.com',
    storageBucket: 'teddysitdb.firebasestorage.app',
    measurementId: 'G-F89RG7F6ZZ',
  );
}
